[env:m5cardputer-adv]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
monitor_speed = 115200
lib_deps = 
    m5stack/M5Cardputer@^1.1.1
build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
